[package]
name = "week7-polarsdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.26.1"
clap = {version="4.0.32", features=["derive"]}